### ISSUE TITLE
Form is setup for travis but not running

### ISSUE THREAD

**Issue by teodozjan** [perl6/ecosystem#101]
https://travis-ci.org/perl6/form has never run even through it has `.travis.yml`

**Comment by jonathanstowe** [comment]
It would appear that there hasn't been a commit since the travis was set up.

**Comment by teodozjan** [comment]
It is one of the few repositories inside perl6 community I'm not able to commit to. Maybe you can try?

**Comment by teodozjan** [comment]
Real commit was not neccessary. Pull request was enough https://github.com/perl6/form/pull/8

**Comment by moritz** [comment]
@teodozjan you should already have write access to perl6/form. Please try it, and contact me if it doesn't work.
