### ISSUE TITLE
Clean Up "Most Wanted" List

### ISSUE THREAD

**Issue by zoffixznet** [perl6/ecosystem#136]
The [Most Wanted Modules List](https://github.com/perl6/perl6-most-wanted/blob/master/most-wanted/modules.md) needs a clean up.

* Clean up WIPs: (my detailed reasoning for proposing a major clean up in for WIPs is described in [this comment](https://github.com/perl6/perl6-most-wanted/pull/15#issuecomment-174599457))
    * Anything that's already listed in the [Ecosystem](http://modules.perl6.org/) should be removed from the Most Wanted list
* Clean up modules already implemented
    * For example, IO::Capture already has at least 3 implementations
* Possibly recategorize what's left.
    * It's a bit hard to see now, but I think reorganizing categories could make the list more useful. For example some things in `Networking` and `Data Formats` could be better placed in a `Web Development` category.

**Comment by Altai-man** [comment]
Your arguments seems wise for me and indeed, it will be easier to see the progress. Regarding that, if nobody has something to argue, it'll be good to remove all WIPs from list.
