### ISSUE TITLE
modules.perl6.org should link each module name to the latest release url

### ISSUE THREAD

**Issue by tbrowder** [perl6/ecosystem#261]
When there are entries to specific commits for a module in the META.list, the latest should be used for the url for that module in the generated modules list on modules.perl6.org.

**Comment by moritz** [comment]
What's the user experience like if we do that? Will the link be a tarball? If yes, then I don't think that's a good idea.

Do you have an example of how it would look like?

**Comment by tbrowder** [comment]
On Monday, October 10, 2016, Moritz Lenz <notifications@github.com> wrote:

> What's the user experience like if we do that? Will the link be a tarball?
> If yes, then I don't think that's a good idea.
>
Per ugexe's commnts, and my current understanding, the url would be to the
release commit tree on the master branch (or any other branch if
appropriate) so the module link on the modules.perl6.org would take the
clicker to that commit tree so he could see the actual released code.

> Do you have an example of how it would look like?
>
I was waiting for confirmation from ugexe that it will work (he may have to
do a little code mod on the ecosystem).  But I will update my module's
current master branch META6.json to show the link.

>

**Comment by JJ** [comment]
Could this be related to #433 ?

**Comment by tbrowder** [comment]
Yes, let's close this.
