### ISSUE TITLE
installation mungs dynamic vars $*PROGRAM and $*PROGRAM-NAME

### ISSUE THREAD

**Issue by tbrowder** [perl6/ecosystem#304]
If an executable program is installed as part of a module via zef (panda not yet tried), the $*PROGRAM and $*PROGRAM-NAME vars report a hash string instead of the name as desired. Examples of Text::More's bin/create-md.p6:

$*PROGRAM-NAME
===============

Uninstalled:
--------------

Usage: ./create-md.p6 ...

Installed:
-----------

Usage: /usr/local/rakudo.d/share/perl6/site/resources/F6AB9B901B7071FBDB38FB8A77B549440AC84EE0 ...

$*PROGRAM
==========

Uninstalled:
---------------

Usage: ./create-md.p6 ...

Installed:
-----------

Usage: /usr/local/rakudo.d/share/perl6/site/resources/F6AB9B901B7071FBDB38FB8A77B549440AC84EE0 ...

Attempted work-around
===================
I also tried '$?FILE' but got the same results.

In the interim I will just hard-code the script name inside the file.

Suggested fix
==========

When zef installs the bin file, save the original file name and use its name to redefine __$*PROGRAM__ and __$*PROGRAM-NAME__.

**Comment by zoffixznet** [comment]
Given the docs for the two variables:
```
$*PROGRAM-NAME	Path to the current executable as it was entered on the command line, or C<-e> if perl was invoked with the -e flag.
$*PROGRAM	Location (in the form of an C<IO::Path> object) of the Perl program being executed.
```

Wouldn't your proposal break all possible usefulness of these variables, save from displaying a name to a human? For example `say "This program has {+$*PROGRAM.lines} of code in it"` will error out with file not found error.

**Comment by jonathanstowe** [comment]
I guess this is somewhat complicated by the original script (which is installed with the hashed name,) being executed by a wrapper which is installed with the original name.

The script is run by the wrapper with something like:

```
 exit run($*EXECUTABLE, @binaries[0].hash.<files><bin/originalname>, @*ARGS).exitcode

```

Where ```@binaries``` is the result of searching for matching distributions.

So as far as everything is concerned when it gets to run the original script the installed hashed name *is* the program name.

I guess the wrapper could set an environment variable with the original name of the script which could then be used by ```USAGE``` if set, or even set some further dynvar (such as ```$*ORIGINAL-PROGRAM-NAME```, but I agree you probably don't want to be changing the ```$*PROGRAM``` or ```$*PROGRAM-NAME``` for the reasons stated.

**Comment by zoffixznet** [comment]
>  which could then be used by USAGE if set

Pretty sure the USAGE is already fixed to display a friendly name

**Comment by jonathanstowe** [comment]
Ah yes, so it is, but it's done by setting an environment variable in the wrapper so for anything installed before that changed it won't be there :-\  I do have a plan to move more of the actual code of the wrapper into Compunit::Respository so it's easier to take advantage of these kind of changes, but obviously that won't help in this case :)

**Comment by jonathanstowe** [comment]
@tbrowder in this case I think it's upgrade your Rakudo if you didn't already and then reinstall the distribution that provides the script with --force - that should get you the *fixed* wrapper :)

**Comment by tbrowder** [comment]
Okay, I wasn't aware of those changes, and I just updated my rakudo to lastest nom branch a few days ago. So that is a reinstall of zef with --force?

**Comment by JJ** [comment]
Ping?

**Comment by zoffixznet** [comment]
This issue has been resolved awhile back.
