### ISSUE TITLE
New module not shared

### ISSUE THREAD

**Issue by ramiroencinas** [perl6/ecosystem#359]
I shared a new module (System::DiskAndUpdatesAlerts) at

https://github.com/perl6/ecosystem/commit/bfa016b75fa535d4f57eb8ecdd05e996a6d3c8e2

, but this module does not yet appear at modules.perl6.org.

Right now the 

https://modules.perl6.org/update.log 

has not been updated since Sun Aug  6 23:04:07 2017

Any ideas? Thanks.

**Comment by zoffixznet** [comment]
> Any ideas? Thanks.

Yeah, yesterday we had a build script issue and... someone... 😅 disabled the updater cron job while debugging it and forgot to put it back on.

It just started now and should finish in about ~1.5hr

**Comment by zoffixznet** [comment]
It's now listed: http://modules.perl6.org/search?q=author%3Aramiro
