### ISSUE TITLE
Rename to .p6 the Perl 6 scripts here

### ISSUE THREAD

**Issue by JJ** [perl6/ecosystem#392]
There are Perl and Perl 6 modules, and it might get a bit confusing.

**Comment by stmuk** [comment]
This is an excellent idea. Systems like Windows require this anyway if Perl 5 and 6 are in use on the same system and the file extension types registered.

**Comment by nxadm** [comment]
.p6, .pm6 and .pod6 (or rather .md, but that's an other can of worms) is the way to go. The .pl and co date from the time when Perl 6 was suppose to supercede 5.

**Comment by nxadm** [comment]
Also, it's important to pick .p6 or .pl6. Not both. Too confusing.

**Comment by JJ** [comment]
I think .p6 is the canonical form now, right?

**Comment by nige123** [comment]
I agree we definitely need something different to Perl 5. 

It's good to avoid confusion on the command-line (and elsewhere too).

I have reservations about anything including the number "6" however:

- it implies a version number - and versions change 
- 6 is unfortunately one higher than 5 - which disenfranchises Perl 5 users - Perl 6 is a different dialect of the language - not a newer version that supplants Perl 5
- for a supposed 100 year language - imagine it's 2030 - won't it be a bit weird that you need a spurious "6" in the filename?

IMHO we really need to [rebrand our favourite dialect of Perl](http://nigelhamilton.com/perl-branding-proposal.html). Once this happens - things like new distinctive file suffixes will follow naturally.

In the meantime we could use .p6 and .pm6 as a placeholder.

**Comment by JJ** [comment]
@nige123 that's a completely different discussion, and this is not the place to have it. As @AlexDaniel says, these are the extensions that are officially recommended now. Maybe move the discussion to perl6/user-experience?

**Comment by AlexDaniel** [comment]
> it implies a version number - and versions change

“6” in “Perl 6” is part of the name now. It's not a version number anymore. Perl 6 will never become Perl 7 or Perl 10. As another data point, we are thinking about an *alias* to the name, and *one* of the proposed aliases is “6lang”. It has a number in it also, but similarly it will never become “7lang”.

> 6 is unfortunately one higher than 5 - which disenfranchises Perl 5 users - Perl 6 is a different dialect of the language - not a newer version that supplants Perl 5

Which is also why we are talking about an alias. See this: https://github.com/perl6/6.d-prep/tree/master/TODO#language-extended-naming

> for a supposed 100 year language - imagine it's 2030 - won't it be a bit weird that you need a spurious "6" in the filename?

In 2030 I'd expect 🦋 in a filename. As for digits vs alpha, no difference for me. It's not spurious, it's part of the name.

**Comment by nxadm** [comment]
I would *love* the renaming as the next guy (.rk for Rakudo!), but in the meantime .p6, .pm6 and .pod6 is a step forward.
