### ISSUE TITLE
Find a solution to the index failing

### ISSUE THREAD

**Issue by JJ** [perl6/ecosystem#454]
This is down: http://ecosystem-api.p6c.org/projects1.json which leads to docker builds and travis tests timing out. Perl6.org has been redirected elsewhere, can we redirect this elsewhere too?

**Comment by JJ** [comment]
Apparently an upgrade to zef by @ugexe has fixed that.

**Comment by Altai-man** [comment]
The link is back, thanks to rba and the infrastructure will be/is expected to become more reliable, plus zef is updated too to avoid timing out, so closing.
Re-open if something else is still needed.
