### ISSUE TITLE
Common instructions for installing modules

### ISSUE THREAD

**Issue by tadzik** [perl6/ecosystem#53]
It's been requested for Bailador: https://github.com/tadzik/Bailador/issues/28; maybe it would be nice to come up with some common README template that we can put in modules for people who found them somehow but have no idea how our Perl 6 ecosystem works.

**Comment by jonathanstowe** [comment]
Yeah I've got quite bored with typing the same thing in the README every time :)

**Comment by tbrowder** [comment]
I submitted PR #260 for this issue.

**Comment by tbrowder** [comment]
I merged the PR which should close this issue unless it doesn't meet your expectations.

**Comment by tbrowder** [comment]
Closed with PR #260.
