### ISSUE TITLE
"Error accessing GitHub API. HTTP Code: 401"

### ISSUE THREAD

**Issue by sdondley** [perl6/ecosystem#606]
I'm trying to track down the source of a problem with zef serving up a stale version of Raku::Pod::Render

Please see: https://github.com/finanalyst/raku-pod-render/issues/11#issuecomment-1170020548

And see https://modules.raku.org/update.log. There are a ton of modules with a "Error accessing GitHub API. HTTP Code: 401" error.

**Comment by patrickbkr** [comment]
There was quite some discussion on IRC. The current best guess is, that REA and modules.raku.org somehow use the API outside of it's limits. Which I don't really understand, because I would have guessed, that these two projects do simple downloads of files on GitHub and don't use the actual API directly at all. (But I might just be wrong about that.)

**Comment by JJ** [comment]
Then it might be that we're becoming popular and went over the minimum rate. As Raku, we can create API tokens; we would have to use it, I guess. But not totally sure whose responsibility is that, other than whoever decides to do it first...

**Comment by sdondley** [comment]
Seems like @lizmat should know.

**Comment by lizmat** [comment]
I don't know anything about modules.raku.org, unfortunately.

Maybe it's time to change modules.raku.org into a redirect to raku.land?

**Comment by sdondley** [comment]
@lizmat that won't solve the bigger problem which is that zef is loading stale modules.

**Comment by sdondley** [comment]
Found another P6C module with the same problem: https://raku.land/github:grondilu/Digest

It's been updated to 0.7.1 but zef info reports 0.7.0.

**Comment by lizmat** [comment]
Hmmm...  it is not being picked up for some reason...  will investigate tomorrow.

**Comment by sdondley** [comment]
I think it's because of all the 401 errors: https://modules.raku.org/update.log

I think it's affecting all P6C modules. Granted, I could be out to lunch on this. That's just my best guess.

**Comment by sdondley** [comment]
Any luck? Curious to know.

**Comment by lizmat** [comment]
A lot of life intervened in the past days.  And am pretty tired today, so it'll be tomorrow.

**Comment by sdondley** [comment]
`zef info Digest` reports correct version now. 0.7.2.
