### ISSUE TITLE
Suggest putting a URL to your project in the commit message

### ISSUE THREAD

**Issue by ab5tract** [perl6/ecosystem#76]
This allows super quick access to the actual thing being added for anyone who is following the repo. Perhaps we could add it as a suggestion in the repo and/or start asking PRs to add it?

**Comment by teodozjan** [comment]
I also would like to take quick view on newly added modules. Now it is not so easy. Or maybe recently added modules on modules.perl6.org?

**Comment by zoffixznet** [comment]
> Or maybe recently added modules on modules.perl6.org?

That [already exists](http://modules.perl6.org/recent.html), though I don't see it linked to from the modules.perl6.org index:

**Comment by zoffixznet** [comment]
Um.. Actually, that "Last Update" is from commit history, not when they were added to the Eco. ¯\_(ツ)_/¯

**Comment by jonathanstowe** [comment]
Yeah sortable, but date added as well :+1:

**Comment by zoffixznet** [comment]
I believe the original topic has been resolved and the stuff mentioned later already has an open Issues in modules.perl6.org repo. I'm closing this Issue for those reasons. :smile_cat:
