### ISSUE TITLE
links to git stars and issues

### ISSUE THREAD

**Issue by MARTIMM** [perl6/ecosystem#99]
E.g. Module 007 stargazers has a link to ```https://github.com/masak/007stargazers``` It is missing a slash and should be like ```https://github.com/masak/007/stargazers```. It is the same for the link to issues.
In this case should be ```https://github.com/masak/007/issues``` instead of ```https://github.com/masak/007issues```.

**Comment by zoffixznet** [comment]
This has now been fixed. Thanks a lot!
http://modules.perl6.org/
